### PR TITLE
CI: fail Jenkins build if tests dont pass

### PR DESCRIPTION
**Pull request by kev-the-dev**
* I think this will make the Jenkins build fail of a unit test fails. Also will display good summary of what tests passed 

* Tested: does FAIL when a test fails, see build PR-222 Run 2

* Tested: still PASSES when all tests pass, see build PR-222 Run 3

### CODE REVIEW

**Comment by DSsoto** [comment]
Can we get colored output from Jenkins?

**Review by DSsoto — APPROVED** [review]

**Comment by sentree** [comment]
This change was well tested, but let me review everything that goes to CI before merging, please.

**Comment by whispercoros** [comment]
This change was well tested, but let me review everything that goes to CI before merging, please.

**Comment by sentree** [comment]
I will add colored output to the list, but there are more important things to do for CI right now.

**Pull request merged**
