### PR TITLE
Switch guess points to interactive markers

### PR DESCRIPTION
**Pull request by LucasBA**

### CODE REVIEW

**Comment by LucasBA** [comment]
Let me test the merge here before anyone pulls it in

**Comment by LucasBA** [comment]
I tested it. It works

**Comment by LucasBA** [comment]
I didnt touch heartbeat or alarms

**Review by RustyBamboo — APPROVED** [review]
Next time be doing `git pull --rebase upstream master` to avoid this merge commits

**Comment by RustyBamboo** [comment]
screenshot_20180727_194547

**Pull request merged**
