### PR TITLE
FORMAT: manually resolve PEP8 conflicts

### PR DESCRIPTION
**Pull request by kev-the-dev**
run ```python2.7 -m flake8 --max-line-length=120 --ignore E731 ./``` on me, I double dog dare you.

### CODE REVIEW

**Comment by sentree** [comment]
Dare accepted. It appears you have failed, sir. This is the output I received from running the command you suggested:

    ./simulation/sub8_gazebo/diagnostics/__init__.py:1:1: F401 'gazebo_tests' imported but unused
    ./simulation/sub8_gazebo/sub8_gazebo_tools/__init__.py:1:1: F401 'BagManager' imported but unused
    ./command/sub8_rqt/sub8_rqt_gui/__init__.py:1:1: F401 'AlarmPlugin' imported but unused
    ./command/sub8_alarm/alarm_handlers/__init__.py:1:1: F401 'HeightOverBottom' imported but unused
    ./command/sub8_alarm/alarm_handlers/__init__.py:2:1: F401 'NetworkLoss' imported but unused
    ./command/sub8_alarm/alarm_handlers/__init__.py:3:1: F401 'ThrusterOut' imported but unused
    ./command/sub8_alarm/alarm_handlers/__init__.py:4:1: F401 'OdomKill' imported but unused
    ./command/sub8_alarm/alarm_handlers/__init__.py:5:1: F401 'Kill' imported but unused
    ./perception/sub8_perception/sub8_vision_tools/machine_learning/__init__.py:1:1: F401 'balanced_resample' imported but unused
    ./perception/sub8_perception/sub8_vision_tools/machine_learning/__init__.py:1:1: F401 'desample_binary' imported but unused
    ./perception/sub8_perception/sub8_vision_tools/machine_learning/__init__.py:2:1: F401 'boost' imported but unused
    ./perception/sub8_perception/sub8_vision_tools/machine_learning/adaboost.py:96:5: F821 undefined name 'bar'
    ./perception/sub8_perception/sub8_vision_tools/machine_learning/adaboost.py:97:5: F821 undefined name 'bar'
    ./perception/sub8_perception/nodes/torpedo_board_pose_est.py:199:17: E126 continuation line over-indented for hanging indent

**Comment by sentree** [comment]
Since I like democracy, I need to get a vote on whether or not people would like to disable PEP8 rule E731. Calling on @DSsoto, @mattlangford, @ironmig, and @RustyBamboo @kingkevlar here. Cast your vote with a thumbs up or a thumbs down.

Personally, I see the appeal of disabling it, but I think it may be better practice to just do things the PEP8 way.

**Comment by kev-the-dev** [comment]
All the __init__ files are ignored. I'll fixed the other two.

**Comment by sentree** [comment]
You're right, I just thought you sounded so confident with the dare and all...

**Comment by sentree** [comment]
So these appear to be the only two issues left:

    ./perception/sub8_perception/sub8_vision_tools/machine_learning/adaboost.py:95:5: F821 undefined name 'bar'
    ./perception/sub8_perception/sub8_vision_tools/machine_learning/adaboost.py:96:5: F821 undefined name 'bar'

The interesting thing is that the command that I ran was `python2.7 -m flake8 --max-line-length=120 --exclude=__init__.py .`, which does not ignore E731. Are we sure this rule is causing us problems?

**Comment by kev-the-dev** [comment]
I can't get that output to happen on my PC. Look at the code, that variable is clearly defined as a global. Are you sure you are running on the latest commit? Maybe the Debian version of flake is different.

**Comment by sentree** [comment]
As long as you make sure that you ran the exact same command that I did in my last comment, I will clear this for merging. We can always fix this issue in #259 if it pops up in the CI builds.

**Review by sentree — APPROVED** [review]
These changes all worked in the simulator.

**Pull request merged**
