### PR TITLE
Simulation: Add widgets, fix numerous issues

### PR DESCRIPTION
**Pull request by jpanikulam**
Bugfixes:
    - Fix monte-carlo issue where sometimes running faster than real-time would cause garbage behavior (You can now run as fast as your computer permits)
    - Fixed some crashes on keyboard press
    - Fixed some crashes related to sub's last force being known
    - Fixed crashes due to typo in visualization
    - Bugs encountered by Patrick
    - Move everything to make_header
    - Fix now-broken PD controller (as a result of sim changes)

Improvements:
    - Add gravitational bias to IMU
    - Add simulator "Widget" for the Sub
    - Add simulator option "demo_mode" particularly for @pemami4911 , demo mode spools up the demo pd controller purely so that it can be used to test the trajectory generator while the sophisticated controllers are still in the oven
    - The demo pd controller does not support waypoints, a PR later this morning will add this feature for demo mode
    - Clean up vehicle sensor publishers
    - Odometry now publishes in the correct frames

Optimizations:
    - tbh I forgot what I did

### CODE REVIEW

**Comment by jpanikulam** [comment]
@tessbianchi

**Comment by tessbianchi** [comment]
Looks good to me!

**Comment by jpanikulam** [comment]
Because I realized it looks odd: Jason and I discussed his comments offline. Buoyancy issue fixed, other things are known issues that will be addresses in future iterations. 

And by offline I mean on the internet, but in a different place on the internet.

**Comment by jnez71** [comment]
This is fine, but it doesn't seem like the buoyancy issue did actually get fixed in this pull.
https://github.com/uf-mil/Sub8/blob/master/simulation/sub8_simulation/sub8_sim_tools/physics/physics.py#L207
Perhaps you missed including that diff?

**Pull request merged**
