### PR TITLE
CAMERAS: Remove camera1394 and fix install script

### PR DESCRIPTION
**Pull request by rleyva**
Removes camera1394 nonsense, ROS Indigo repo contains latest build.

### CODE REVIEW

**Comment by jpanikulam** [comment]
This deletes the calibration and launch files for the cameras, was that your intention?

**Comment by rleyva** [comment]
Fixed.

**Comment by jpanikulam** [comment]
7,000 deletions!

**Comment by mattlangford** [comment]
Can't launch sim now :[
`ResourceNotFound: camera1394`

**Comment by mattlangford** [comment]
Hmm after running the dependencies script I'm running into compilation errors when it gets to
`#include <gazebo/sensors/DepthCameraSensor.hh>`

**UPDATE**
Deleting catkin /devel and /build folders and remaking seemed to work.
Still running into issues launch the simulator.
`<include file="$(find camera1394)/launch/stereo.launch"/>`
Do we have a stereo launch file anywhere?

**Comment by jpanikulam** [comment]
Ah, crap, that was just moved to sub8_launch/subsystems

**Comment by mattlangford** [comment]
I will update that for my next PR

**Pull request merged**
