### PR TITLE
DIAGNOSTICS: add thruster visualizer

### PR DESCRIPTION
**Pull request by kev-the-dev**

### CODE REVIEW

**Comment by kev-the-dev** [comment]
screenshot from 2017-07-09 21-18-22

**Review by RustyBamboo — APPROVED** [review]

**Review by DSsoto — APPROVED** [review]
This is great, can you add it to sub8.launch?

**Comment by DSsoto** [comment]
Feature request if you want to take it on:
* Vary the color with the magnitude.

Something easier if you don't want to do that is:
* Get the bounds and use a specific color (like red) to indicate that a thruster is being saturated.

It would be a good aid to gnc visualization.

**Comment by kev-the-dev** [comment]
Arrows now go from green (near-zero thrust) to yellow (near limits), with red reserved for exactly equal to limits.

screenshot from 2017-07-10 14-08-43

**Pull request merged**
