### PR TITLE
ALARMS: Remove spurious log-err's

### PR DESCRIPTION
**Pull request by jpanikulam**
- Removes the confusing big red errors that show up on start-up
- Adds an example launch for making the alarm system do anything at all

### CODE REVIEW

**Comment by jpanikulam** [comment]
Also updated license

**Comment by LucasBA** [comment]
This is fantastic

**Comment by jpanikulam** [comment]
@zachgoins ?

**Comment by zachgoins** [comment]
Literally LOLing. Way too loud, almost, in a crowded airport. Close one.

**Pull request merged**
