### PR TITLE
SIM: Many minor bugfixes and improvements

### PR DESCRIPTION
**Pull request by jpanikulam**
Many minor bugfixes/improvements
- Fixed some ODE-initiated crashes
- Fixed the Sub sometimes not colliding with the Transdec
- Added transparent water
- Added mesh rendering
- Added mesh physics
- Added cached mesh loading (Will load a big .obj file, then cache it as a .npz)
- Added web-storage of meshes
  - Big meshes, >20MB will be stored on Google drive, and then downloaded to your computer as necessary
  - Simul8 will automatically check if the meshes you currently have are out of date
  - It will also automatically unzip zip files, and generate an .npz cache!
- Add service for setting the position/velocity of the Sub
- Add indicator arrows for showing velocity
- Fix render-distance causing weird behavior
- Add geometry_helper for making a rotation matrix that aligns one vector with another

The size of this commit is vastly overstated, because it includes a 2,000 line binary file. It looks like this is included in the line count. In reality, it is about 700 line deltas, most of them very minor.

### CODE REVIEW

**Comment by jpanikulam** [comment]
What happens re: @pemami4911 's PR if this is pulled ?

**Comment by pemami4911** [comment]
We cause a fracture in the git space-time continuum

**Comment by jpanikulam** [comment]
Brought up to date.

Now it's 3,700 lines because it is counting Patrick's commits. I have no idea what will happen when we try to merge this.

**Comment by rleyva** [comment]
Approve @pemami4911

**Comment by jpanikulam** [comment]
Pulling post approval by @rleyva

**Comment by jpanikulam** [comment]
Uh-oh, it retroactively cherry-picked Patrick's commits. @pemami4911 can you confirm that you are still able to pull from upstream master? If not, I'll revert this and fix it.

**Comment by pemami4911** [comment]
Was able to pull successfully, I have all of the latest commits.

On Wed, Oct 14, 2015 at 2:28 AM, Jake notifications@github.com wrote:

> Uh-oh, it retroactively cherry-picked Patrick's commits. @pemami4911
> https://github.com/pemami4911 can you confirm that you are still able
> to pull from upstream master? If not, I'll revert this and fix it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uf-mil/Sub8/pull/22#issuecomment-147950830.

## 

_Patrick Emami_
University of Florida, '16
Department of Computer & Information Science & Engineering
Computer Engineering Major
(c) : 904-962-8293

**Pull request merged**
